# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempbill', '0002_auto_20170811_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billmedicine',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='billmedicine',
            name='medicine',
        ),
        migrations.AddField(
            model_name='medicine',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='BillMedicine',
        ),
    ]
