# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tempbill', '0003_auto_20170811_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='cost',
            new_name='unit_cost',
        ),
    ]
