# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempbill', '0005_billitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='number',
            field=models.IntegerField(),
        ),
    ]
