# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tempbill', '0007_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='bill',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tempbill.Bill'),
            preserve_default=False,
        ),
    ]
