# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempbill', '0010_bill_billitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_time',
            field=models.DateTimeField(default=0),
            preserve_default=False,
        ),
    ]
