# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tempbill', '0013_auto_20170811_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billitem',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='billitem',
            name='medicine',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='BillItem',
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
