# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-21 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0002_auto_20170821_1156'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tax.TaxGroup'),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tax.TaxGroup'),
        ),
        migrations.AddField(
            model_name='itemstockbatch',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tax.TaxGroup'),
        ),
    ]
